library(nlme)
library(lme4)
library(sjPlot)

library(ggplot2)
library(ggpubr)
library(tidyverse)
library(broom)

df=read.csv('C:/Users/Hanna/Documents/GitHub/LRDC-Research/SCA_Merge/SCAloose.csv')
View(df)

#compared against Chinese and Level 3
#MODELS FOR EACH OF THE SCA VALEUS
W=lme4::lmer(W~L1+as.factor(level_id)+(1|anon_id)+(1|question_id),REML=FALSE,data=df)
S=lme4::lmer(S~L1+as.factor(level_id)+(1|anon_id)+(1|question_id),REML=FALSE,data=df)
VP=lme4::lmer(VP~L1+as.factor(level_id)+(1|anon_id)+(1|question_id),REML=FALSE,data=df)
C=lme4::lmer(C~L1+as.factor(level_id)+(1|anon_id)+(1|question_id),REML=FALSE,data=df)
T=lme4::lmer(T~L1+as.factor(level_id)+(1|anon_id)+(1|question_id),REML=FALSE,data=df)
DC=lme4::lmer(DC~L1+as.factor(level_id)+(1|anon_id)+(1|question_id),REML=FALSE,data=df)
CT=lme4::lmer(CT~L1+as.factor(level_id)+(1|anon_id)+(1|question_id),REML=FALSE,data=df)
CP=lme4::lmer(CP~L1+as.factor(level_id)+(1|anon_id)+(1|question_id),REML=FALSE,data=df)
CN=lme4::lmer(CN~L1+as.factor(level_id)+(1|anon_id)+(1|question_id),REML=FALSE,data=df)
MLS=lme4::lmer(MLS~L1+as.factor(level_id)+(1|anon_id)+(1|question_id),REML=FALSE,data=df)
MLT=lme4::lmer(MLT~L1+as.factor(level_id)+(1|anon_id)+(1|question_id),REML=FALSE,data=df)
MLC=lme4::lmer(MLC~L1+as.factor(level_id)+(1|anon_id)+(1|question_id),REML=FALSE,data=df)
C.S=lme4::lmer(C.S~L1+as.factor(level_id)+(1|anon_id)+(1|question_id),REML=FALSE,data=df)
VP.T=lme4::lmer(VP.T~L1+as.factor(level_id)+(1|anon_id)+(1|question_id),REML=FALSE,data=df)
C.T=lme4::lmer(C.T~L1+as.factor(level_id)+(1|anon_id)+(1|question_id),REML=FALSE,data=df)
DC.C=lme4::lmer(DC.C~L1+as.factor(level_id)+(1|anon_id)+(1|question_id),REML=FALSE,data=df)
DC.T=lme4::lmer(DC.T~L1+as.factor(level_id)+(1|anon_id)+(1|question_id),REML=FALSE,data=df)
T.S=lme4::lmer(T.S~L1+as.factor(level_id)+(1|anon_id)+(1|question_id),REML=FALSE,data=df)
CT.T=lme4::lmer(CT.T~L1+as.factor(level_id)+(1|anon_id)+(1|question_id),REML=FALSE,data=df)
CP.T=lme4::lmer(CP.T~L1+as.factor(level_id)+(1|anon_id)+(1|question_id),REML=FALSE,data=df)
CP.C=lme4::lmer(CP.C~L1+as.factor(level_id)+(1|anon_id)+(1|question_id),REML=FALSE,data=df)
CN.T=lme4::lmer(CN.T~L1+as.factor(level_id)+(1|anon_id)+(1|question_id),REML=FALSE,data=df)
CN.C=lme4::lmer(CN.C~L1+as.factor(level_id)+(1|anon_id)+(1|question_id),REML=FALSE,data=df)


models
summary(LMER)
par(mfrow=c(2,2))
plot(LMER)


sum=function(model){
  summary=summary(model)
  return(summary)
}
sum(W)
sjPlot::plot_model(W)
sum(S)
sjPlot::plot_model(S)
sum(VP)
sjPlot::plot_model(VP)
sum(C)
sjPlot::plot_model(C)
sum(T)
sjPlot::plot_model(T)
sum(CT)
sjPlot::plot_model(CT)
sum(CP)
sjPlot::plot_model(CP)
sum(CN)
sjPlot::plot_model(CN)
sum(MLS)
sjPlot::plot_model(MLS)
sum(MLT)
sjPlot::plot_model(MLT)
sum(MLC)
sjPlot::plot_model(MLC)
sum(C.S)
sjPlot::plot_model(C.S)
sum(VP.T)
sjPlot::plot_model(VP.T)
sum(C.T)
sjPlot::plot_model(C.T)
sum(DC.C)
sjPlot::plot_model(DC.C)
sum(DC.T)
sjPlot::plot_model(DC.T)
sum(T.S)
sjPlot::plot_model(T.S)
sum(CT.T)
sjPlot::plot_model(CT.T)
sum(CP.T)
sjPlot::plot_model(CP.T)
sum(CP.C)
sjPlot::plot_model(CP.C)
sum(CN.T)
sjPlot::plot_model(CN.T)
sum(CN.C)
sjPlot::plot_model(CN.C)


#interact lvlid and lang
intLMER=lme4::lmer(W~L1*as.factor(level_id)+(1|anon_id)+(1|question_id),REML=FALSE,data=df)
intLMER

summary(intLMER)
par(mfrow=c(2,2))
plot(intLMER)

sjPlot::plot_model(intLMER)
